version: "3.9"

services:
  web:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "/wait-for-postgres.sh db python manage.py migrate &&
             python manage.py load_seed_data --csv=data/seed_shipments.csv &&
             python manage.py runserver 0.0.0.0:9000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: parcels
      POSTGRES_USER: parcelsuser
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
