[tool.isort]
profile = "django"
combine_as_imports = true
include_trailing_comma = true
line_length = 80
skip_glob = ["*/grpc/*"]


[tool.black]
line-length = 80
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | .*/grpc/.*
)/
'''
