# Generated by Django 5.2.1 on 2025-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="carrier",
            field=models.CharField(
                choices=[
                    ("DHL", "Dhl"),
                    ("UPS", "Ups"),
                    ("DPD", "Dpd"),
                    ("FedEx", "Fedex"),
                    ("GLS", "Gls"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("in-transit", "In Transit"),
                    ("inbound-scan", "Inbound Scan"),
                    ("delivery", "Delivery"),
                    ("transit", "Transit"),
                    ("scanned", "Scanned"),
                ],
                max_length=20,
            ),
        ),
    ]
